#!/bin/bash
declare -i N
N=0
end=300
#i=1
#terminal=2
prestrength=0
initialstrength=0
strength=0
prestrength=$initialstrength
#-------------------------------------
while [ "  $N " -lt " $end " ]
do
i=`expr $N + 1 `
echo $N,$strength
./flysim.out -s rough -t 2

strength=`gawk -v pres=$prestrength 'BEGIN{stre=0;}
{ 
	stre=pres+30;
       }
END{print stre;}' network.pro`


sed -i 6s/$prestrength/$strength/g network.pro
sed -i 18s/$N/$i/g network.pro
prestrength=$strength

N=`expr $N + 1 `
done
echo "job complete"
#./multifile_firing_rate
./mean_stdev2_test.scr

